/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {


    public static void main(String[] args) {
       Hewan obyekHewan =  new Hewan();
       obyekHewan.cetakNama("Elang");
    }
}
